Switch to using JWTKit v5
vapor/jwt pull request #149
Opened 2023-11-06 21:42 UTC by ptoffy

This PR starts lining out how the package is going to look after JWTKit updates to v5. 
Currently one test is failing which is expected. It's probably going to be fixed after https://github.com/vapor/jwt-kit/pull/112 is merged

2023-11-06 22:08 UTC, 0xTim commented
@ptoffy want to convert this to a draft PR?

2023-11-06 22:09 UTC, 0xTim commented on Package.swift
Need to enable strict concurrency checking to this as well, that will reveal a few more issues

2024-02-21 20:08 UTC, 0xTim approved these changes

2024-02-21 20:08 UTC, 0xTim commented on Package.swift
>          .package(url: "https://github.com/vapor/vapor.git", from: "4.50.0"),
Lets bump this to the latest

2024-02-21 20:09 UTC, 0xTim commented on Package.swift
>          .package(url: "https://github.com/vapor/vapor.git", from: "4.50.0"),
Blah

2024-02-21 20:09 UTC, 0xTim requested changes

2024-02-21 20:09 UTC, 0xTim commented on Package.swift
>          .package(url: "https://github.com/vapor/vapor.git", from: "4.50.0"),
Adding nothing to make GH work

2024-02-22 11:42 UTC, 0xTim commented
@ptoffy something got broke

2024-02-22 11:48 UTC, ptoffy commented
> @ptoffy something got broke

Yeah that was me confidently editing from the web interface 🤦‍♂️

2024-02-27 10:39 UTC, 0xTim approved these changes

2024-02-27 11:53 UTC, merged